image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off  # использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info